apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:  
    storageclass.kubernetes.io/is-default-class: "true"  # Marks this as default StorageClass  
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.122.229
  share: /data2/pvc
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
